[package]
name = "relay"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

cli-args.workspace = true
builder-primitives.workspace = true

reth-payload-builder = { workspace = true }

grpc.workspace = true
tonic.workspace = true

reth = { workspace = true }
url = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
serde_derive = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }

futures-util = { workspace = true }
hex = { workspace = true }
consensus_layer.workspace = true
warp = { workspace = true }
chrono = { workspace = true }

reqwest = { version = "0.11", features = ["json"] }

parking_lot = { workspace = true }
tracing = { workspace = true }
ssz_rs = { version = "0.9.0",features = ["serde"] }

tree_hash = "0.5"
tree_hash_derive = "0.5"
ethereum_ssz = "0.5"
ethereum_ssz_derive = "0.5"
ethereum_serde_utils = "0.5"

blst = { version = "0.3.3" }
flate2 = "1.0.28"



[dev-dependencies]
rand = "0.8.5"
temp-env = { version = "0.3.4", features = ["async_closure"] }
